language: python
matrix:
  include:
  - env: DIST=doc
  - env: DIST=mypy
  - env: DIST=pep8
  - env: DIST=pytest_centos_8
  - env: DIST=pytest_debian_buster
  - env: DIST=pytest_fedora_31
  - env: DIST=pytest_fedora_32
  - env: DIST=pytest_ubuntu_bionic
  - env: DIST=pytest_ubuntu_focal
  - env: DIST=rpm_centos_8
  - env: DIST=rpm_fedora_32
sudo: required
services:
- docker
before_install:
- true
install:
- docker build . -t ${DIST} -f docker/${DIST}.docker
before_script:
- true
script:
- true
deploy:
  provider: pypi
  user: gijzelaerr
  password:
    secure: X0E+bGnLZQa4QVU6wDMN3o5qs4fjBzo+7cCKAdSf0WpyV8VwCLaaXCXMgr64i3cH7lpv0/pRGGRKJ3l84xZd3OAmVDFbNAAdq3rxhVKJxugjB7QfF+1//U5hpBuWctswEukcvWyj3kUAFzw7P0Mn9r8kxcveNEoDpzpHqP7nKI9BBvZw2oMGZ/RT8FqR+E4aj36WorvmVraURa5TG+hD8v1r7iPqUE2GDdNDwSyO8AQ82vumTXNEvX54TjDZEkVR8tsFVnPpgcK3exuqWe9kVK/6+iJnkDDatGqBa/NdljObRhV7zvxoRfDvI5PKyCF4joZO99UTzWvQtS57lqYvTFgLwba1w9UgIrbM3YthJNwlyv9QXDs2WPpmuzCaAow7I1yJTmiHMX+NCIsQ/TQ2UoHd11qk2eqYgY/IAZvNZPHmCe1uHYJdDibTbdXa2gXMfGAxqAZhu+mEOvbbH+hWdPWJjBOuvh/Q9gRwZMBwqF9OUB92m4PfzHuxivMCAiG67iPlrxIGmpP90EQ5XwNeOtqgfQMLnNq3N/utD0sUUT1WlBqeQOJzL3POdYuuKDj6c4Bs2El9VLwy5JRbBqupToxWcZRR103xA94dqa2ZzBxf19EVgc26gtBAZV7wvDP1NQ97UGQChlenqpLzSartb1sGty+KO3t79qzE2cZdHts=
  skip_existing: true
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: eduvpn/python-eduvpn-client
notifications:
  email:
    on_fail: always
